### ISSUE TITLE
Github authentication failed

### ISSUE THREAD

**Issue by licianeandreatta** [call4paperz/call4paperz#100]
Hello.

My name is Liciane Andreatta and after I've registered with my GitHub account, my account have been created as a "Leonardo Saraiva".

I've also just changed his name to "Leonardo Saraiva (edited for github issue)"

This is happening live on http://call4paperz.com/

**Comment by ricardovaleriano** [comment]
:scream: :scream: :scream:

@licianeandreatta, VERY strange issue. I'll look into it asap.

**Comment by ricardovaleriano** [comment]
@licianeandreatta, please, can you send me the email that is associated with your github account? Send it to `ricardo.valeriano@gmail.com`, please.

**Comment by licianeandreatta** [comment]
Hello

The email is licianecristina@gmail.com.

Thanks

On Tue, Feb 24, 2015 at 4:37 PM, Ricardo Valeriano <notifications@github.com
> wrote:

> @licianeandreatta <https://github.com/licianeandreatta>, please, can you
> send me the email that is associated with your github account? Send it to
> ricardo.valeriano@gmail.com, please.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ricardovaleriano/call4paperz/issues/100#issuecomment-75829197>
> .
>



-- 
Atenciosamente

Liciane Andreatta
Fone: 8807-6667

**Comment by ricardovaleriano** [comment]
@licianeandreatta Sorry for be so late on this issue.
Can you please retry to create your account now?

**Comment by wsilva** [comment]
First of all I tried to register using e-mail and password but I am not receiving confirmation e-mail to enable my account. I always receive the flash message: "You have to confirm your account before continuing. " 

After it tried to register using my github account (by the way it uses the same e-mail address) but after the app authorization inside github I were redirected to login page with the same flash message: "You have to confirm your account before continuing."

Then I tried to login with Twitter with success. But when I try to add a proposal in a event I am redirected to fill my profile. I was able to add a picture and change my name with success but when I try to add my e-mail address (the same) it shows as saved but if I try to review my profile it is not there anymore. 

Seems to be an issue with e-mail address filter ou validation or something like that.

**Comment by lucianosousa** [comment]
@licianeandreatta @wsilva guys, still happening with you this problem?

**Comment by wsilva** [comment]
@lucianosousa yep same thing. When I try to log with my gihub account: "You have to confirm your account before continuing. " ... but no confirmation e-mail yet. Even if I try to log in using e-mail and password recovery or confirmation e-mail resend functionality...

**Comment by lucianosousa** [comment]
I'll work on this until next week. Hope fix it.

**Comment by lucianosousa** [comment]
@licianeandreatta @wsilva can you take a look on it again? Sorry being so late.
We did few improves on the website. Hope this problem go away.

**Comment by lucianosousa** [comment]
Closing since it looks fine.
