### ISSUE TITLE
Search and destroy unused dependencies.

### ISSUE THREAD

**Issue by ricardovaleriano** [call4paperz/call4paperz#103]
I have a feeling that we have code and dependencies that aren't used anymore. Would be great to just remove these stuff.

**Comment by lucianosousa** [comment]
@ricardovaleriano can you give us some detail about what you think isn't used anymore?

**Comment by ricardovaleriano** [comment]
No details up in my sleeve! XD
In fact this issue was here to remember me to verify if there are those unused dependencies.

**Comment by lucianosousa** [comment]
There is nothing to do about it. Thanks for the issue
