### ISSUE TITLE
Add `spring` gem.

### ISSUE THREAD

**Issue by ricardovaleriano** [call4paperz/call4paperz#106]
Now that we have `rails4` =)

**Comment by lucianosousa** [comment]
@tauil @viniciussbs @aoqfonseca what do you guys think about it?

**Comment by aoqfonseca** [comment]
It's look like interesting... we can use this ....

**Comment by rodrigopinto** [comment]
@lucianosousa totally agree! :+1:

**Comment by lucianosousa** [comment]
related to PR #131

**Comment by viniciussbs** [comment]
:+1:

**Comment by tauil** [comment]
Excellent! :+1:

**Comment by lucianosousa** [comment]
done with PR #131
