### ISSUE TITLE
No avatar broke layout

### ISSUE THREAD

**Issue by lucianosousa** [call4paperz/call4paperz#138]
Chrome:
![screen shot 2016-02-15 at 4 09 29 pm](https://cloud.githubusercontent.com/assets/44833/13056798/bfe7f6fc-d3fe-11e5-9d76-c0a01630b60f.png)

Firefox:
![screen shot 2016-02-15 at 4 09 09 pm](https://cloud.githubusercontent.com/assets/44833/13056825/061bf4f2-d3ff-11e5-85bf-deef3ba213d8.png)

**Comment by lucianosousa** [comment]
@tauil can u help on this issue?

**Comment by tauil** [comment]
Sure.

**Comment by lucasrenan** [comment]
@lucianosousa do you have any idea why the avatar is missing by a given user?

also, do you have a link with broken avatars?

**Comment by lucianosousa** [comment]
@lucasrenan I supposed the person doesnt have a gravatar account. The project uses it to capture the avatar.

**Comment by lucasrenan** [comment]
@lucianosousa got it. will have a check. thanks.

**Comment by rodrigopinto** [comment]
Would be nice to have a fallback image, the person has no gravatar.

**Comment by lucasrenan** [comment]
@lucianosousa I couldn't find anything from gravatar in the project.

@rodrigopinto actually, there's a fallback as you can see here: https://github.com/call4paperz/call4paperz/blob/master/app/helpers/user_helper.rb#L6

somehow, images are being found in production: http://call4paperz.com/assets/no_avatar.png

**Comment by tauil** [comment]
Fixed! :beers:
