### ISSUE TITLE
markdown on event infos ?

### ISSUE THREAD

**Issue by lucianosousa** [call4paperz/call4paperz#141]
Looks like really useful and easier than some WYSIWYG

**Comment by tauil** [comment]
Agreed.

**Comment by lucasrenan** [comment]
@lucianosousa do you any idea on how to do it? store the "htmlled" version in another field or just convert the markdown to html on every call?

**Comment by lucianosousa** [comment]
I'm thinking in use this JS: https://github.com/NextStepWebs/simplemde-markdown-editor
for the web editor; save it as markdown text plain; render it as html(maybe with JS or any ruby gem;

**Comment by lucianosousa** [comment]
I'll work on this issue until Monday. If it's not done till there, feel free to do it if you are reading this message <3

**Comment by lucianosousa** [comment]
done on #199
