### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by paulodiovani** [call4paperz/call4paperz#144]
Hello,

I believe there is some authentication problem on call4paperz website. I tried to authenticate with GitHub and it loaded this profile info:

![screenshot from 2016-07-01 18-36-51](https://cloud.githubusercontent.com/assets/1295197/16535125/52cda85e-3fbb-11e6-87d5-53da7544439b.png)

**Comment by tauil** [comment]
We'll take a look Paulo. Thanks for reporting.

**Comment by jonasporto** [comment]
@tauil I was analysing the codebase and I ended up solving this error in a [pull request](https://github.com/call4paperz/call4paperz/pull/146).

**Comment by tauil** [comment]
@paulodiovani I've just finished deploying a possible fix (since a could not reproduce your problem with my user). Can you please check if your problem was fixed?

**Comment by paulodiovani** [comment]
I don't think it's solved. 
This certainly is not my e-mail.

![screenshot from 2016-07-04 11-19-51](https://cloud.githubusercontent.com/assets/1295197/16563598/5f6f7e64-41d9-11e6-922f-f55929603c35.png)
![screenshot from 2016-07-04 11-20-04](https://cloud.githubusercontent.com/assets/1295197/16563599/5f768d62-41d9-11e6-91cc-33e49a2a116d.png)

**Comment by paulodiovani** [comment]
The problem is possibly due to mu e-mail adress being private. To test, change your's on Settings page as follows.

![screenshot from 2016-07-04 11-22-06](https://cloud.githubusercontent.com/assets/1295197/16563685/cf9ef9da-41d9-11e6-8eaa-8d8313480b88.png)

**Comment by tauil** [comment]
Can you test something to me?

Do the following steps:
1. Logout;
2. Got to your [Github authorized apps page](https://github.com/settings/applications);
3. Revoke Call4paprez access. It should be a C4P app with an avatar of the old maintainer (we'll fix that later);
4. Login again with Github
5. Check if your user profile changes.

**Comment by paulodiovani** [comment]
@tauil This was the test I did earlier. And there was no new commit after that.

**Comment by tauil** [comment]
Ok @paulodiovani ! Thanks for this information. 

Tonight I'll do some more tests and work on it. Probably I'll have to change the authentication to update email and Personal info after each login.

**Comment by lucianosousa** [comment]
@paulodiovani we already fix this issue. do you know if your login is working right now?

**Comment by tauil** [comment]
Sorry @lucianosousa and @paulodiovani I forgot to mention that Paulo already tried to log
in again and looks like he logged in but his profile didn't update.

We decided to **not merge** the [update profile on every login feature](https://github.com/call4paperz/call4paperz/pull/147), so @paulodiovani can you just update your profile manually? Sorry for this but looks like this problem won't happen again in the future.

**Comment by paulodiovani** [comment]
Ok, @tauil
