### ISSUE TITLE
Edit proposal name

### ISSUE THREAD

**Issue by matheus-vieira** [call4paperz/call4paperz#148]
Hello I would like to change the proposal name at this link:

http://call4paperz.com/events/2-tech-day-do-guru-pr/proposals/2341

Actually I thought that the field "Name" was really related to my my name, but after that I figured out that should be the proposal title then, please, change to **Testes Automatizados com NodeJS, Selenium e o framework TheIntern**

And my suggestion would be to change the label with the text "Name" to a more descriptive text like "Proposal Name" or "Proposal Title" this way is more clear to the user what the field is.

**Comment by lucianosousa** [comment]
@matheus-vieira For security reasons, you cannnot change a proposal name after 30min. 

You are not the only one suffering about it.

What I think we need to do is: put a better warning about it, and also, as you said, improve this `proposal name`.

@tauil what do you think about?

**Comment by tauil** [comment]
We never had that problem, but we'll take this suggestion for the next release. The proposal name is updated.

**Comment by tauil** [comment]
Never knew that other people had that problem! Anyway... it's partially solved. Let's take the label name suggestion to the next release.
