### ISSUE TITLE
Add code climate to PR check

### ISSUE THREAD

**Issue by lucasrenan** [call4paperz/call4paperz#150]
Is it possible to add code climate check for PRs?

**Comment by tauil** [comment]
Yes and it's free for open source projects like this but I think that it's sort of the same idea of `coveralls` so I don't think that make sense to keep both. We should pick one. @lucianosousa feedback?

**Comment by lucianosousa** [comment]
@tauil coveralls is for test coverage. codeclimate is for code quality.
I'll try add this plugin here.

**Comment by lucasrenan** [comment]
:+1

**Comment by tauil** [comment]
👍 👍

**Comment by lucasrenan** [comment]
@lucianosousa if I'm not wrong, there's a config you can setup in github for code climate make a check for every opened PR, like the one we already have for travis and hakiri.

**Comment by lucianosousa** [comment]
@lucasrenan tried this yesterday but didn't work.
I think it's a problem with the token I used. I'll keep working on it

**Comment by lucasrenan** [comment]
@lucianosouza looks like its working. should we close this issue?

**Comment by lucianosousa** [comment]
closed! ;)
