### ISSUE TITLE
Fix error pages

### ISSUE THREAD

**Issue by lucasrenan** [call4paperz/call4paperz#161]
Error pages are currently with layout errors

http://call4paperz.com/404
http://call4paperz.com/500

the google analytics code may be wrong either.

**Comment by jonasporto** [comment]
I can't get reproduce this bug, But at development mode, the page opens with a poorly stylesheet.

![call4paper-404](https://cloud.githubusercontent.com/assets/2723477/17905995/ac87d9be-694b-11e6-84d5-bd3d8a33851d.png)

**Comment by lucasrenan** [comment]
@jonasporto to reproduce the error, just check:

http://call4paperz.com/404
http://call4paperz.com/500

in dev I'm getting the same page as you are.
