### ISSUE TITLE
Donation service to support infrastructure

### ISSUE THREAD

**Issue by lucianosousa** [call4paperz/call4paperz#183]
https://flattr.com/
or
https://www.patreon.com/

**Comment by tauil** [comment]
http://nonprofithub.org/nonprofit-technology/5-online-donation-tools-to-delight-your-donors/

https://doublethedonation.com/donation-tools-and-services-for-nonprofits/

**Comment by lucianosousa** [comment]
@tauil nice. I'll take look on it

**Comment by lucasrenan** [comment]
👍

**Comment by hugonomura** [comment]
:+1:

**Comment by lucianosousa** [comment]
After read some articles about it, I decided to just add few adsense banners, if someone wants to talk about it feel free to ask me

**Comment by lucasrenan** [comment]
@lucianosousa fair enough

**Comment by tauil** [comment]
Ok to me.
