### ISSUE TITLE
Use docker

### ISSUE THREAD

**Issue by lucasrenan** [call4paperz/call4paperz#185]
What do you guys think in using docker for development?

**Comment by hugonomura** [comment]
@lucasrenan there is a branch called Docker.
I think Ricardo Valeriano created this sometime ago.
I tried to use, but I have some problems.
We can work on a update for this branch. What you think? :)

**Comment by lucasrenan** [comment]
@hugonomura good idea. also @kleberngueriero may join us :)

**Comment by tauil** [comment]
I encourage you, but I rather use Vagrant.

**Comment by lucasrenan** [comment]
@tauil any problems with docker?

**Comment by tauil** [comment]
When I tried I got some zombie process using it. But that was two years ago and then I never needed to change or test it again anymore.

**Comment by lucianosousa** [comment]
I just did a:

`$ docker-compose run --rm web bin/setup`

and received the following error:
```
PG::ConnectionBad: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

It's related to DB config.
`Couldn't create database for {"adapter"=>"postgresql", "database"=>"call4paperz_development", "username"=>"luciano", "password"=>nil, "min_messages"=>"WARNING"}`

For better use, I suggest we describe a better workflow to properly setup the app.

**Comment by lucasrenan** [comment]
@lucianosousa I may be wrong, but I think you have to start the db first, like:

`docker-compose start db` in background or run both containers in a separate terminal tab: `docker-compose run`

**Comment by lucianosousa** [comment]
didn't work.

it's related to DB username. generates the `database.yml` with wrong username. `luciano`(my system username) instead of `postgres`

**Comment by kleberngueriero** [comment]
@lucianosousa, it seems that it happened because you should update your database.yml.
I suppose your database.yml still point to localhost only, but the new database.yml.sample have a condition to use a environment variable(created in the container) if it exists, and localhost only if it doesn't.

And about the use of docker-compose.override.yml for development, I'm going to create a new branch for updating the README to talk about that.

**Comment by lucianosousa** [comment]
@kleberngueriero still doesn't work. I think it's a problem here:
https://github.com/call4paperz/call4paperz/blob/master/bin/setup#L53

username should be `postgres` on database.yml

**Comment by lucasrenan** [comment]
@kleberngueriero good job!

**Comment by lucianosousa** [comment]
<3

**Comment by kleberngueriero** [comment]
thanks!
