### ISSUE TITLE
Enable HTML or Markdown tags on event description and paper description

### ISSUE THREAD

**Issue by CesarNog** [call4paperz/call4paperz#195]
It would be nice to be able to add HTML or Markdown tags on event description and paper description.

Related to: https://github.com/call4paperz/call4paperz/issues/141

**Comment by tauil** [comment]
Agreed

**Comment by lucasrenan** [comment]
this duplicated issue should be closed in favour of https://github.com/call4paperz/call4paperz/issues/141

**Comment by tauil** [comment]
Good catch @lucasrenan
