### ISSUE TITLE
Shall we move the json endpoints to a real API?

### ISSUE THREAD

**Issue by lucasrenan** [call4paperz/call4paperz#230]
I notice we provide content via json, like:

http://call4paperz.com/events.json
http://call4paperz.com/events/cocoaheads-12-edicao.json

I wonder if anyone is using it? if so, shall we refactor the code or even move to a separate API? 🤔

**Comment by tauil** [comment]
Agreed. This will be useful for a future SPA front-end.

**Comment by lucasrenan** [comment]
@tauil btw, do you believe call4paperz is a good fit for SPA? how is google currently indexing pages served by SPAs?

**Comment by tauil** [comment]
No idea about it. It's been a long time since I last studied and worked with SEO.

**Comment by tauil** [comment]
And yes. I believe that SPA is a good fit for this project because it's so small and simple, also, I think it will add a good dynamic to the project.

**Comment by lucasrenan** [comment]
it's fine for "CUD", but for "read" actions, we must check if google would be able to index the content.

**Comment by lucianosousa** [comment]
I suggest remove these JSON calls right now (nobody uses it, I guess)
I'm looking to start an Android app, so, later API calls will makes sense
also, update rails to 5.x prior to that ;)
