### ISSUE TITLE
Update to Rails 5

### ISSUE THREAD

**Issue by lucasrenan** [call4paperz/call4paperz#233]
We currently rely on Rails 4, which is not maintained anymore. We have to update!

**Comment by tauil** [comment]
👍

**Comment by lucianosousa** [comment]
I'm working on it

**Comment by lucasrenan** [comment]
@lucianosousa cool! let me know if you need any help :)

**Comment by lucianosousa** [comment]
related to #234

**Comment by lucianosousa** [comment]
done
