### ISSUE TITLE
Shutdown call4paperz?

### ISSUE THREAD

**Issue by vinibaggio** [call4paperz/call4paperz#246]
Olá pessoal!

Recebi um email para renovar o domínio do call4paperz. Não vejo muita movimentação no site, e por isso estava pensando em não renovar. O que acham?

**Comment by lucasrenan** [comment]
@akitaonrails a codeminer nao tem interesse em tocar esse projeto? seria
legal para os juniors praticarem :)

**Comment by tauil** [comment]
Fala @vinibaggio ! Cara o site tem acesso sim... tem uma galera que usa.

Dá uma olhada:
<img width="499" alt="screen shot 2018-08-26 at 18 47 40" src="https://user-images.githubusercontent.com/14328/44630613-a2ea0380-a960-11e8-8a49-c21c08d83cc3.png">

Acho que derrepente é o caso de ver com o @lucianosousa se ele tem interesse de pegar o domínio pois até onde sei ele é quem banca o Call4paperz no momento.

**Comment by lucianosousa** [comment]
@vinibaggio me manda o esquema do domínio aí. vou renovar

**Comment by tauil** [comment]
Assim que resolverem a questão do domínio, não esqueçam de fechar essa issue!

**Comment by vinibaggio** [comment]
Beleza!

**Comment by tauil** [comment]
Some more info that I just get to endorse why we should keep it.

<img width="416" alt="screen shot 2018-09-05 at 09 56 04" src="https://user-images.githubusercontent.com/14328/45079125-fb07cf00-b0f1-11e8-8c4f-94a9a0885e09.png">

Besides this, all good with the domain?

**Comment by gustavokloh** [comment]
Domain renewed. I'm closing this issue.

**Comment by tauil** [comment]
@gustavokloh let me know if you want the admin access to the Google Analytics.
