### ISSUE TITLE
Remove travis-ci integration

### ISSUE THREAD

**Issue by lucianosousa** [call4paperz/call4paperz#251]
I've tried to do this in the past but didn't finish.

Circle CI is doing this job right now and all builds that runs successfully stays with the pending check
see: https://github.com/call4paperz/call4paperz/pull/250

**Comment by lucasrenan** [comment]
@lucianosousa I can have a look into it

**Comment by lucianosousa** [comment]
@lucasrenan please! ;D

thanks

**Comment by lucasrenan** [comment]
@gustavokloh I don't have enough permissions to disable travis-ci. could you disable the integration, please?

**Comment by lucasrenan** [comment]
@lucianosousa apparently, CircleCI builds are only running for your PRs, can you check it please or give me access to it?

**Comment by lucasrenan** [comment]
@gustavokloh currently, we have four PRs blocked by this issue:

https://github.com/call4paperz/call4paperz/pull/248
https://github.com/call4paperz/call4paperz/pull/249
https://github.com/call4paperz/call4paperz/pull/252
https://github.com/call4paperz/call4paperz/pull/253

**Comment by lucianosousa** [comment]
done
