### ISSUE TITLE
Upgrade for last version of Ruby and Rails

### ISSUE THREAD

**Issue by frankyston** [call4paperz/call4paperz#296]
Ruby 2.6.2
Rails 5.2.3

**Comment by frankyston** [comment]
Irei fazer essa atualização.

**Comment by frankyston** [comment]
PR: https://github.com/call4paperz/call4paperz/pull/297

**Comment by frankyston** [comment]
Neste PR foi também foi corrigido a implementação do Tag list, pois na nova versão ele funciona diferente do que estava implementado anteriormente.

**Comment by lucasrenan** [comment]
@frankyston please write the comments in english :)

**Comment by frankyston** [comment]
I am closing this PR because I will be updating individually ruby and rails in separate Pull Requests.
