### ISSUE TITLE
Group Page

### ISSUE THREAD

**Issue by lucianosousa** [call4paperz/call4paperz#32]
Sometimes, I wanna find some old event from some ruby group and it's annoying try find that.
A Group Page with current(future) and past events section is a good way.
:)

**Comment by lucianosousa** [comment]
related to #107

**Comment by lucasrenan** [comment]
@lucianosousa @tauil will this feature be implemented or we can close the issue?

**Comment by tauil** [comment]
@lucasrenan From what I remember, @lucianosousa is working on it.

**Comment by lucianosousa** [comment]
it can be closed. I'm working on tags now.
