### ISSUE TITLE
Update ruby 2.5.1 to 2.6.5

### ISSUE THREAD

**Issue by frankyston** [call4paperz/call4paperz#326]
Upgrade ruby to the latest version.

**Comment by frankyston** [comment]
I'll get this issue.

**Comment by frankyston** [comment]
PR: https://github.com/call4paperz/call4paperz/pull/327

**Comment by lucasrenan** [comment]
@frankyston why did you close the PR?

**Comment by frankyston** [comment]
@lucasrenan I changed it for this pr https://github.com/call4paperz/call4paperz/pull/336

**Comment by frankyston** [comment]
merged
