### ISSUE TITLE
Bug on Sign up screen

### ISSUE THREAD

**Issue by italomatos** [call4paperz/call4paperz#330]
![Captura de Tela 2019-10-03 às 21 41 07](https://user-images.githubusercontent.com/836472/66173474-b0bf8d00-e626-11e9-89a2-319814e364cd.png)

error message on footer in signup screen.

**Comment by lucasrenan** [comment]
@italomatos did the sign up worked out?

**Comment by italomatos** [comment]
> @italomatos did the sign-up work?

yes, it did.
