### ISSUE TITLE
Login with Google Account problem

### ISSUE THREAD

**Issue by italomatos** [call4paperz/call4paperz#335]
I tried login in with my Google account, but I received this error:
![Captura de Tela 2019-10-06 às 19 00 16](https://user-images.githubusercontent.com/836472/66276716-cffb2c00-e86b-11e9-9aad-829e30c5c374.png)

**Comment by frankyston** [comment]
@italomatos This issue has been resolved, I believe @diegopolido must have updated OAuth keys
