### ISSUE TITLE
Create button in registration screen doesn't appear

### ISSUE THREAD

**Issue by italomatos** [call4paperz/call4paperz#340]
I'm trying to register in call4paperz.com , but, when I filled all fields, then button doesn't appear.

You can see on image.
![Captura de Tela 2019-10-14 às 14 54 36](https://user-images.githubusercontent.com/836472/66772393-00a61b80-ee93-11e9-93e4-b477c45cedc5.png)

**Comment by frankyston** [comment]
@italomatos vou pegar essa issue.

**Comment by frankyston** [comment]
PR: https://github.com/call4paperz/call4paperz/pull/344
