### ISSUE TITLE
Allow organizers to access speaker's and user's e-mails.

### ISSUE THREAD

**Issue by interney** [call4paperz/call4paperz#54]
Speaker's e-mails -> To contact the speaker in order to announce if their proposal was accepted.
User's e-mails -> To contact everyone that upvoted in a proposal to invite them to register in the event.

**Comment by lucasrenan** [comment]
@ricardovaleriano what's missing for this issue?

**Comment by ricardovaleriano** [comment]
@lucascaton I sincerely don't know man. XD Sorry, this goes waaay back in the past.
The main issue was that the organisers have no way to contact the speakers. We were trying to solve this.
But I don't know what I did or what is missing anymore =(

**Comment by lucasrenan** [comment]
@ricardovaleriano ok, no worries.

@interney do you have any idea what's missing?

**Comment by lucascaton** [comment]
@ricardovaleriano wrong Lucas :stuck_out_tongue_winking_eye:

**Comment by ricardovaleriano** [comment]
> @ricardovaleriano wrong Lucas

hahahahaha sorry, mate! 💃

**Comment by interney** [comment]
@lucasrenan I'm no longer using the call4paperz, this issue was almost 2 years ago, I really can't remember, sorry...

**Comment by lucasrenan** [comment]
@lucianosousa @tauil should we close this issue?

**Comment by lucianosousa** [comment]
@lucasrenan I think what we have on production nowadays works fine.
For me it's OK to close.

@tauil ?

**Comment by tauil** [comment]
If there's no way to contact the speakers, I vote to work on this feature.

**Comment by lucasrenan** [comment]
@tauil there's a list of speakers contacts, for the event creator.

**Comment by tauil** [comment]
So it's ok to close this.
